BOOKING_STATUS_PENDING = "PENDING"
BOOKING_STATUS_CONFIRMED = "CONFIRMED"
BOOKING_STATUS_RESERVED = "RESERVED"
BOOKING_STATUS_ACTIVE = "ACTIVE"
BOOKING_STATUS_COMPLETED = "COMPLETED"
BOOKING_STATUS_CANCELLED = "CANCELLED"
BOOKING_STATUS_REJECTED = "REJECTED"

BOOKING_STATUSES = [
    BOOKING_STATUS_PENDING,
    BOOKING_STATUS_CONFIRMED,
    BOOKING_STATUS_RESERVED,
    BOOKING_STATUS_ACTIVE,
    BOOKING_STATUS_COMPLETED,
    BOOKING_STATUS_CANCELLED,
    BOOKING_STATUS_REJECTED,
]

BOOKING_STATUS_LABELS = {
    BOOKING_STATUS_PENDING: "Pending",
    BOOKING_STATUS_CONFIRMED: "Confirmed",
    BOOKING_STATUS_RESERVED: "Reserved",
    BOOKING_STATUS_ACTIVE: "Active",
    BOOKING_STATUS_COMPLETED: "Completed",
    BOOKING_STATUS_CANCELLED: "Cancelled",
    BOOKING_STATUS_REJECTED: "Rejected",
}

BLOCKING_BOOKING_STATUSES = [
    BOOKING_STATUS_CONFIRMED,
    BOOKING_STATUS_RESERVED,
    BOOKING_STATUS_ACTIVE,
]

CAR_STATUS_AVAILABLE = "AVAILABLE"
CAR_STATUS_RESERVED = "RESERVED"
CAR_STATUS_RENTED = "RENTED"
CAR_STATUS_MAINTENANCE = "MAINTENANCE"
CAR_STATUS_INACTIVE = "INACTIVE"

CAR_STATUSES = [
    CAR_STATUS_AVAILABLE,
    CAR_STATUS_RESERVED,
    CAR_STATUS_RENTED,
    CAR_STATUS_MAINTENANCE,
    CAR_STATUS_INACTIVE,
]

CAR_CATEGORIES = [
    "Economy",
    "Sedan",
    "SUV",
    "Luxury",
    "Sports",
    "Van",
]

CAR_IMAGE_ANGLES = [
    "Front",
    "Front Angle",
    "Side",
    "Rear Angle",
    "Rear",
    "Top",
    "Interior",
    "Detail",
]

TRANSMISSIONS = ["Automatic", "Manual"]

FUEL_TYPES = ["Petrol", "Diesel", "Hybrid", "Electric"]

DEFAULT_CURRENCY = "$"

# --- Loyalty ---
# Balance needed before a customer can turn points into a reward.
LOYALTY_REDEEM_THRESHOLD = 1000
# What a redeemed balance buys: 5% off the next rental.
LOYALTY_DISCOUNT_PERCENT = 5